### ISSUE TITLE
half pyramid pattern

### ISSUE THREAD

**Issue by Raj-Kharwar-26** [Romeo-Aryal/C-program-fest2022#66]
I want to contribute code of half pyramid pattern of * in C.  Accept it and give hacktober fest label.

**Comment by Himanshu-Vishwas** [comment]
@Raj-Kharwar-26 please assign me this issue

**Comment by Himanshu-Vishwas** [comment]
@Romeo-Aryal Please assign me this issue

**Comment by Pratibha0280** [comment]
Assign me this issue

**Comment by vipingautam07** [comment]
Please assign me, I will do my best!
